# Generated by Django 5.1.7 on 2025-04-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголок статьи", max_length=150, verbose_name="Заголовок"),
                ),
                ("contents", models.TextField(help_text="Введите ваш тект публикации", verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blogs/photo", verbose_name="Изображение"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_activ",
                    models.BooleanField(
                        default=True, help_text="Признак публикации", verbose_name="Признак публикации"
                    ),
                ),
                (
                    "count_views",
                    models.IntegerField(
                        blank=True, help_text="Количество просмотров", null=True, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ["title", "created_at"],
            },
        ),
    ]
