# Generated by Django 5.1.7 on 2025-04-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blogs_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogs",
            name="count_views",
        ),
        migrations.AddField(
            model_name="blogs",
            name="views_count",
            field=models.PositiveIntegerField(
                blank=True, default=0, help_text="Счетчик просмотров", null=True, verbose_name="Количество просмотров"
            ),
        ),
    ]
