# Generated by Django 5.1.7 on 2025-04-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_blogs_count_views_blogs_views_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="is_activ",
            new_name="is_active",
        ),
        migrations.RemoveField(
            model_name="blogs",
            name="product",
        ),
    ]
