# Generated by Django 5.1.7 on 2025-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Опишите категорию", null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта", max_length=150, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Введите описание продукта", max_length=250, verbose_name="Описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изоброжение продукта",
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                ("category", models.CharField(max_length=150, verbose_name="Категория")),
                ("price", models.IntegerField(verbose_name="Цена за покупку")),
                ("created_at", models.DateField(max_length=150, verbose_name="Дата создания")),
                ("updated_at", models.DateField(max_length=150, verbose_name="Дата последнего изменения")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "price"],
            },
        ),
    ]
